export const data_dashboard = [
  {
    category: "background",
    media: "./dashboard/pic1.png",
    description: "cuteeee",
    username: "gm73",
    userProfile: "./user_profile/profile1.jpg",
  },
  {
    category: "illustration",
    media: "./dashboard/pic2.jpg",
    description: "lovelyy",
    username: "frost346",
    userProfile: "./user_profile/profile2.png",
  },
  {
    category: "graphics",
    media: "./dashboard/pic3.jpg",
    description: "woww",
    username: "fabric43",
    userProfile: "./user_profile/profile3.jpg",
  },
  {
    category: "pandas",
    media: "./dashboard/pic4.jpg",
    description: "wonderful",
    username: "delivery346",
    userProfile: "./user_profile/profile4.jpg",
  },
  {
    category: "love",
    media: "./dashboard/pic5.jpg",
    description: "ayieee",
    username: "hum234",
    userProfile: "./user_profile/profile5.jpg",
  },
  {
    category: "fashion",
    media: "./dashboard/pic6.jpg",
    description: "trendyy",
    username: "pansy723",
    userProfile: "./user_profile/profile6.jpg",
  },
  {
    category: "eyeglasses",
    media: "./dashboard/pic7.jpg",
    description: "Glasses",
    username: "admit843",
    userProfile: "./user_profile/profile7.jpg",
  },
  {
    category: "notes",
    media: "./dashboard/pic8.jpg",
    description: "nice",
    username: "deal83",
    userProfile: "./user_profile/profile8.jpg",
  },
  {
    category: "english",
    media: "./dashboard/pic9.jpg",
    description: "languages",
    username: "trousers344",
    userProfile: "./user_profile/profile9.jpg",
  },
  {
    category: "chinese",
    media: "./dashboard/pic10.jpg",
    description: "learning 101",
    username: "buff999",
    userProfile: "./user_profile/profile10.png",
  },
  {
    category: "life",
    media: "./dashboard/pic11.jpg",
    description: "peace",
    username: "equestrian575",
    userProfile: "./user_profile/profile11.jpg",
  },
  {
    category: "hair",
    media: "./dashboard/pic12.jpg",
    description: "wow",
    username: "jellied78373",
    userProfile: "./user_profile/profile12.png",
  },
  {
    category: "zodiac",
    media: "./dashboard/pic13.png",
    description: "exciting",
    username: "liberal783",
    userProfile: "./user_profile/profile13.png",
  },
  {
    category: "projects",
    media: "./dashboard/pic14.png",
    description: "youthful",
    username: "boom763",
    userProfile: "./user_profile/profile14.png",
  },
  {
    category: "events",
    media: "./dashboard/pic15.png",
    description: "lovely",
    username: "enchant621",
    userProfile: "./user_profile/profile15.png",
  },
  {
    category: "tourist spots",
    media: "./dashboard/pic16.jpg",
    description: "pink",
    username: "sneeze555",
    userProfile: "./user_profile/profile16.png",
  },
  {
    category: "architecture",
    media: "./dashboard/pic17.jpg",
    description: "Pictures",
    username: "shoe53",
    userProfile: "./user_profile/profile17.png",
  },
  {
    category: "IT",
    media: "./dashboard/pic18.png",
    description: "Saves",
    username: "carpal82",
    userProfile: "./user_profile/profile18.png",
  },
  {
    category: "web design",
    media: "./dashboard/pic19.jpg",
    description: "Graphics",
    username: "unreeve41",
    userProfile: "./user_profile/profile19.png",
  },
  {
    category: "italian",
    media: "./dashboard/pic20.jpg",
    description: "language 101",
    username: "display52",
    userProfile: "./user_profile/profile20.jpg",
  },
  {
    category: "gifts",
    media: "./dashboard/pic21.jpg",
    description: "wonderful",
    username: "order52",
    userProfile: "./user_profile/profile21.jpg",
  },
  {
    category: "memes",
    media: "./dashboard/pic22.jpg",
    description: "funny",
    username: "breakdown75275",
    userProfile: "./user_profile/profile22.png",
  },
  {
    category: "clothes",
    media: "./dashboard/pic23.jpg",
    description: "dazzling",
    username: "forceful7522753",
    userProfile: "./user_profile/profile23.png",
  },
  {
    category: "portfolio",
    media: "./dashboard/pic24.jpg",
    description: "wonderful",
    username: "dolls555",
    userProfile: "./user_profile/profile24.png",
  },
  {
    category: "layout",
    media: "./dashboard/pic25.jpg",
    description: "design",
    username: "fortress455",
    userProfile: "./user_profile/profile25.jpg",
  },
  {
    category: "internet35",
    media: "./dashboard/pic26.jpg",
    description: "nice",
    username: "diorite",
    userProfile: "./user_profile/profile26.jpg",
  },
  {
    category: "layout643",
    media: "./dashboard/pic27.jpg",
    description: "graphics",
    username: "smoggy",
    userProfile: "./user_profile/profile27.jpg",
  },
  {
    category: "illustration675",
    media: "./dashboard/pic28.jpg",
    description: "wowie",
    username: "squad",
    userProfile: "./user_profile/profile28.jpg",
  },
  {
    category: "grahics76676",
    media: "./dashboard/pic29.jpg",
    description: "<3 <3 <3 <3",
    username: "mend",
    userProfile: "./user_profile/profile29.jpg",
  },
  {
    category: "life870",
    media: "./dashboard/pic30.jpg",
    description: "tranquil life",
    username: "game",
    userProfile: "./user_profile/profile30.jpg",
  },
  {
    category: "shoes324",
    media: "./dashboard/pic31.jpg",
    description: "collectibles",
    username: "rout",
    userProfile: "./user_profile/profile31.jpg",
  },
  {
    category: "chinese designs",
    media: "./dashboard/pic32.jpg",
    description: "art",
    username: "moorhen352",
    userProfile: "./user_profile/profile32.jpg",
  },
  {
    category: "coding",
    media: "./dashboard/pic33.jpg",
    description: "tips and tricks",
    username: "example141",
    userProfile: "./user_profile/profile33.jpg",
  },
  {
    category: "drawing tips",
    media: "./dashboard/pic34.jpg",
    description: "tips and tricks",
    username: "still333",
    userProfile: "./user_profile/profile34.jpg",
  },
  {
    category: "photoshop",
    media: "./dashboard/pic35.jpg",
    description: "graphics, shortcuts",
    username: "network314",
    userProfile: "./user_profile/profile35.jpg",
  },
  {
    category: "tourist spots",
    media: "./dashboard/pic36.jpg",
    description: "nature",
    username: "choke366",
    userProfile: "./user_profile/profile36.jpg",
  },
  {
    category: "architecture",
    media: "./dashboard/pic37.png",
    description: "structures",
    username: "chowder32434",
    userProfile: "./user_profile/profile37.jpg",
  },
  {
    category: "chinese",
    media: "./dashboard/pic38.jpg",
    description: "language 101",
    username: "threatened7657",
    userProfile: "./user_profile/profile38.jpg",
  },
  {
    category: "web design",
    media: "./dashboard/pic39.jpeg",
    description: "designss",
    username: "ore9999",
    userProfile: "./user_profile/profile39.jpg",
  },
  {
    category: "zodiac",
    media: "./dashboard/pic40.jpg",
    description: "excited",
    username: "nugget666",
    userProfile: "./user_profile/profile40.jpg",
  },
  {
    category: "background",
    media: "./dashboard/pic41.jpg",
    description: "phone bg",
    username: "grip2345",
    userProfile: "./user_profile/profile41.jpg",
  },
  {
    category: "illustration",
    media: "./dashboard/pic42.jpg",
    description: "cute",
    username: "actually2222",
    userProfile: "./user_profile/profile42.jpg",
  },
  {
    category: "layout",
    media: "./dashboard/pic43.jpg",
    description: "simple",
    username: "hoe2424",
    userProfile: "./user_profile/profile43.jpg",
  },
  {
    category: "graphics",
    media: "./dashboard/pic44.jpg",
    description: "minimalistic",
    username: "expression8989",
    userProfile: "./user_profile/profile44.jpg",
  },
  {
    category: "shopping",
    media: "./dashboard/pic45.jpg",
    description: "trendy",
    username: "latticed5565",
    userProfile: "./user_profile/profile45.jpg",
  },
  {
    category: "stage design",
    media: "./dashboard/pic46.jpg",
    description: "cool design",
    username: "nap888",
    userProfile: "./user_profile/profile46.jpg",
  },
  {
    category: "hair",
    media: "./dashboard/pic47.jpg",
    description: "colors",
    username: "mazipan565",
    userProfile: "./user_profile/profile47.jpg",
  },
  {
    category: "eyeglasses",
    media: "./dashboard/pic48.jpg",
    description: "lovely",
    username: "clover5655",
    userProfile: "./user_profile/profile48.jpg",
  },
  {
    category: "chinese",
    media: "./dashboard/pic49.jpg",
    description: "wonderful",
    username: "cistus888",
    userProfile: "./user_profile/profile49.jpg",
  },
  {
    category: "zodiac",
    media: "./dashboard/pic50.jpg",
    description: "my year",
    username: "rescue222",
    userProfile: "./user_profile/profile50.jpg",
  },
];
