export const products = [
  {
    name: "Laptop",
    price: 999.99,
    origPrice: 1099.99,
    brand: "Dell",
    description: '15.6" Full HD, Intel Core i7, 16GB RAM, 512GB SSD',
    quantity: 50,
    picture: "./pics/1.jpg",
  },
  {
    name: "Smartphone",
    price: 699.99,
    origPrice: 799.99,
    brand: "Apple",
    description: '6.5" OLED Display, 128GB Storage, Triple Camera Setup',
    quantity: 30,
    picture: "./pics/2.webp",
  },
  {
    name: "Headphones",
    price: 149.99,
    origPrice: 199.99,
    brand: "Sony",
    description: "Wireless Over-Ear Headphones with Active Noise Cancellation",
    quantity: 100,
    picture: "./pics/3.jpg",
  },
  {
    name: "Smartwatch",
    price: 249.99,
    origPrice: 299.99,
    brand: "Samsung",
    description: "Waterproof Fitness Tracker with Heart Rate Monitor",
    quantity: 80,
    picture: "./pics/4.webp",
  },
  {
    name: "Camera",
    price: 799.99,
    origPrice: 899.99,
    brand: "Canon",
    description: "24MP DSLR Camera with 18-55mm Lens Kit",
    quantity: 25,
    picture: "./pics/5.jpg",
  },
  {
    name: "Tablet",
    price: 399.99,
    origPrice: 499.99,
    brand: "Samsung",
    description: '10.2" Retina Display, 128GB Storage, A12 Bionic Chip',
    quantity: 0,
    picture: "./pics/6.jpg",
  },
  {
    name: "Gaming Console",
    price: 499.99,
    origPrice: 599.99,
    brand: "Microsoft",
    description: "4K HDR Gaming Console with 1TB SSD",
    quantity: 15,
    picture: "./pics/7.jpg",
  },
  {
    name: "Wireless Speaker",
    price: 129.99,
    origPrice: 149.99,
    brand: "Bose",
    description: "Bluetooth Speaker with 20 Hours Battery Life",
    quantity: 60,
    picture: "./pics/8.jpg",
  },
  {
    name: "Drone",
    price: 899.99,
    origPrice: 999.99,
    brand: "DJI",
    description: "4K Camera Drone with GPS and Intelligent Flight Modes",
    quantity: 0,
    picture: "./pics/9.jpg",
  },
  {
    name: "External Hard Drive",
    price: 129.99,
    origPrice: 149.99,
    brand: "Seagate",
    description: "2TB USB 3.0 Portable External Hard Drive",
    quantity: 35,
    picture: "./pics/10.jpg",
  },
  {
    name: "Fitness Tracker",
    price: 79.99,
    origPrice: 99.99,
    brand: "Fitbit",
    description: "Activity Tracker with Heart Rate Monitor and Sleep Tracking",
    quantity: 75,
    picture: "./pics/11.jpg",
  },
  {
    name: "Wireless Earbuds",
    price: 129.99,
    origPrice: 149.99,
    brand: "Apple",
    description: "True Wireless Earbuds with Noise Cancellation",
    quantity: 0,
    picture: "./pics/12.jpg",
  },
  {
    name: "Monitor",
    price: 299.99,
    origPrice: 349.99,
    brand: "LG",
    description: '27" QHD IPS Monitor with Thin Bezels',
    quantity: 45,
    picture: "./pics/13.webp",
  },
  {
    name: "Portable Projector",
    price: 199.99,
    origPrice: 249.99,
    brand: "Epson",
    description: "1080p Mini Projector with Built-in Speakers",
    quantity: 25,
    picture: "./pics/14.jpg",
  },
  {
    name: "Wireless Keyboard and Mouse",
    price: 79.99,
    origPrice: 89.99,
    brand: "Logitech",
    description: "Wireless Keyboard and Mouse Combo with Long Battery Life",
    quantity: 70,
    picture: "./pics/15.jpg",
  },
  {
    name: "Electric Scooter",
    price: 499.99,
    origPrice: 599.99,
    brand: "Segway",
    description: "Foldable Electric Scooter with 15.5 MPH Top Speed",
    quantity: 0,
    picture: "./pics/16.webp",
  },
  {
    name: "Coffee Maker",
    price: 69.99,
    origPrice: 79.99,
    brand: "Keurig",
    description: "Programmable Coffee Maker with 12-Cup Capacity",
    quantity: 30,
    picture: "./pics/17.webp",
  },
  {
    name: "Rice Cooker",
    price: 49.99,
    origPrice: 59.99,
    brand: "Zojirushi",
    description: "8-Cup Rice Cooker with Steam Basket",
    quantity: 40,
    picture: "./pics/18.jpg",
  },
  {
    name: "Air Purifier",
    price: 149.99,
    origPrice: 169.99,
    brand: "Levoit",
    description: "True HEPA Air Purifier for Home Allergies and Pets",
    quantity: 0,
    picture: "./pics/19.jpg",
  },
  {
    name: "Electric Toothbrush",
    price: 39.99,
    origPrice: 45.99,
    brand: "Philips",
    description: "Rechargeable Electric Toothbrush with Timer",
    quantity: 50,
    picture: "./pics/20.webp",
  },
];
